image: docker:stable

stages:
  - test
  - build
  - deploy

# -------------------------- API --------------------------

test-api:
  stage: test
  image: maven:3.6-jdk-11
  script:
    - cd API/digital-booking-c3-e-1
    - mvn clean test jacoco:prepare-agent jacoco:report
    - ls target/site/jacoco/
  artifacts:
    paths:
      - API/digital-booking-c3-e-1/target/surefire-reports/
      - API/digital-booking-c3-e-1/target/site/jacoco/
  only:
    changes:
      - API/digital-booking-c3-e-1/**/*
      - develop
      

build-api:
  stage: build
  image: maven:3.6-jdk-11
  script:
    - cd API/digital-booking-c3-e-1
    - mvn clean package -DskipTests=true
  artifacts:
    paths:
      - API/digital-booking-c3-e-1/target/equipamiento-deportivo.jar
  only:
    changes:
      - API/digital-booking-c3-e-1/**/*
      - develop


deploy_to_ec2:
  stage: deploy
  image: alpine:3.11
  before_script:
    - apk update && apk add openssh-client bash
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - touch ~/.ssh/config
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh-keyscan -H $EC2_INSTANCE_IP >> ~/.ssh/known_hosts
  script:
    - ssh ubuntu@$EC2_INSTANCE_IP "sudo systemctl stop equipamiento-deportivo.service"
    - scp API/digital-booking-c3-e-1/target/equipamiento-deportivo.jar ubuntu@$EC2_INSTANCE_IP:~/equipamiento-deportivo/
    - ssh ubuntu@$EC2_INSTANCE_IP "sudo systemctl start equipamiento-deportivo.service"
  only:
    changes:
      - API/digital-booking-c3-e-1/**/*
      - develop